name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the ${{ github.ref_name }} branch
        uses: actions/checkout@v3
      - name: Scan for security vulnerabilities
        uses: aufdenpunkt/python-safety-check@master
        env:
          DEP_PATH: requirements.txt
      - id: auth
        name: Establish authentication to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/239616190043/locations/global/workloadIdentityPools/chatbot/providers/chatbot-provider
          service_account: chatbot@comp7940chatbot-347611.iam.gserviceaccount.com
      - id: deploy
        name: Deploy from source to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: telegram-cattybot
          region: asia-east2
          env_vars: |
            DB_HOST=34.96.231.6
            DB_PORT=3306
            DB_NAME=chatbot
            SEARCH_LIMIT=100
            PAGE_LIMIT=10
          secrets: |
            TELEGRAM_ACCESS_TOKEN=TELEGRAM_ACCESS_TOKEN:latest
            TELEGRAM_WEBHOOK_SECRET_PATH=TELEGRAM_WEBHOOK_SECRET_PATH:latest
            DB_USERNAME=DB_USERNAME:latest
            DB_PASSWORD=DB_PASSWORD:latest
          project_id: comp7940chatbot-347611
          source: .
      - name: Set webhook URL
        run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_ACCESS_TOKEN }}/setWebhook?max_connections=100&url=${{ steps.deploy.outputs.url }}/${{ secrets.TELEGRAM_WEBHOOK_SECRET_PATH }}"